#!/usr/bin/env python3
"""Emit sw/rope_vectors.h -- compiled-in test vectors for the bare-metal C test.

Uses the same golden model as the RTL testbenches, so a pass in software confirms that
the *software* view agrees too: instruction encoding, operand packing, and the
half-split / interleaved whole-vector loops.

Usage:
    python3 model/gen_c_vectors.py [--n 64] [--out sw/rope_vectors.h]
"""

import argparse
import sys

import numpy as np

from bf16 import bf16_to_f32, to_bf16
from rope_ref import (
    DEFAULT_BASE,
    phi_table,
    rope_strict_bf16,
    rope_vector_strict_bf16,
)

# Keep the vector count modest: this array is linked into a bare-metal image that may
# live in a small simulated memory.
DEFAULT_N = 64

CHAIN_STEPS = 8
CHAIN_M = 13
CHAIN_I = 3


def emit(n, d, base):
    phi = phi_table(d, base)
    half = d // 2
    rng = np.random.default_rng(20240803)

    # --- per-instruction vectors ------------------------------------------------
    # Mix ordinary activation-range values with a few full-mantissa ones so the
    # multiplications genuinely round.
    x = to_bf16(rng.uniform(-4.0, 4.0, size=n))
    y = to_bf16(rng.uniform(-4.0, 4.0, size=n))
    # Full 16-bit m range: rope_pkg::PosBits is 16 to match the rs2[31:16] field, and
    # exercising m > 8191 from software is what proves the ISA field is honoured
    # end to end rather than truncated somewhere in the coprocessor.
    m = rng.integers(0, 65536, size=n)
    i = rng.integers(0, half, size=n)

    xr, yr = rope_strict_bf16(x, y, m.astype(np.uint64), i, phi)

    rs1 = [(int(x[k]) << 16) | int(y[k]) for k in range(n)]
    rs2 = [(int(m[k]) << 16) | int(i[k]) for k in range(n)]
    rd = [(int(xr[k]) << 16) | int(yr[k]) for k in range(n)]

    # --- dependent chain -------------------------------------------------------
    # Repeatedly rotate the SAME pair, feeding each result into the next instruction.
    # This is what exercises the core's forwarding into the registered-operand path.
    acc_x = np.array([int(x[0])], dtype=np.uint16)
    acc_y = np.array([int(y[0])], dtype=np.uint16)
    for _ in range(CHAIN_STEPS):
        acc_x, acc_y = rope_strict_bf16(
            acc_x, acc_y, CHAIN_M, np.array([CHAIN_I]), phi
        )
    chain_expected = (int(acc_x[0]) << 16) | int(acc_y[0])

    # --- whole-head vectors, both conventions ----------------------------------
    head_in = to_bf16(rng.uniform(-4.0, 4.0, size=d))
    head_m = 137
    out_hs = rope_vector_strict_bf16(head_in, head_m, phi, convention="half_split")
    out_il = rope_vector_strict_bf16(head_in, head_m, phi, convention="interleaved")

    L = []
    w = L.append
    w("/* ---------------------------------------------------------------------------")
    w(" * rope_vectors.h -- GENERATED by model/gen_c_vectors.py. DO NOT EDIT BY HAND.")
    w(" *")
    w(f" * Golden-model vectors for d={d}, base={base:g}, produced by the same")
    w(" * model/rope_ref.py used by the RTL testbenches.")
    w(" * ------------------------------------------------------------------------- */")
    w("")
    w("#ifndef ROPE_VECTORS_H")
    w("#define ROPE_VECTORS_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w(f"#define ROPE_NUM_VECTORS {n}u")
    w(f"#define ROPE_HEAD_DIM    {d}u")
    w(f"#define ROPE_HEAD_M      {head_m}u")
    w(f"#define ROPE_CHAIN_STEPS {CHAIN_STEPS}u")
    w(f"#define ROPE_CHAIN_M     {CHAIN_M}u")
    w(f"#define ROPE_CHAIN_I     {CHAIN_I}u")
    w(f"#define ROPE_CHAIN_EXPECTED 0x{chain_expected:08X}u")
    w("")

    def arr(name, values, width, per_line=6):
        w(f"static const uint{width}_t {name}[] = {{")
        fmt = "0x%0{}X".format(width // 4)
        for j in range(0, len(values), per_line):
            chunk = values[j : j + per_line]
            w("    " + ", ".join((fmt % v) + "u" for v in chunk) + ",")
        w("};")
        w("")

    arr("rope_vec_rs1", rs1, 32)
    arr("rope_vec_rs2", rs2, 32)
    arr("rope_vec_rd", rd, 32)

    arr("rope_head_in", [int(v) for v in head_in], 16, per_line=8)
    arr("rope_head_out_half_split", [int(v) for v in out_hs], 16, per_line=8)
    arr("rope_head_out_interleaved", [int(v) for v in out_il], 16, per_line=8)

    w("#endif /* ROPE_VECTORS_H */")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=DEFAULT_N)
    ap.add_argument("--d", type=int, default=128)
    ap.add_argument("--base", type=float, default=DEFAULT_BASE)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    text = emit(args.n, args.d, args.base)
    with open(args.out, "w") as f:
        f.write(text)
    print(f"wrote {args.out} ({args.n} instruction vectors, d={args.d})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
