// -----------------------------------------------------------------------------
// rope_theta_rom.sv -- GENERATED by gen/gen_theta_rom.py. DO NOT EDIT BY HAND.
//
// Integer phase increments for RoPE:  Phi_i = round(2^32 * theta_i / 2pi)
// with theta_i = base^(-2i/d),  d = 128,  base = 10000.
//
// These are INTEGERS by design (INV-2). The phase word is an address used to index
// the sine LUT; it is never multiplied by or added to BF16 data. A 32-bit phase
// makes 'mod 2*pi' free (natural wraparound) and has zero drift.
//
// Size: 64 entries x 32 bits = 256 bytes.
// -----------------------------------------------------------------------------

module rope_theta_rom #(
  parameter int unsigned HeadDim   = 128,
  parameter int unsigned NumPairs  = 64,   // HeadDim/2
  parameter int unsigned PhaseBits = 32
) (
  input  logic [5:0]            pair_idx_i,   // i, the frequency index
  output logic [PhaseBits-1:0]  phi_o         // Phi_i
);

  // Combinational ROM. Small enough (see size above) that synthesis maps this to
  // logic cleanly; no memory macro required.
  always_comb begin
    unique case (pair_idx_i)
      6'd0  : phi_o = 32'h28BE60DC;  // theta_0 = 1.000000000e+00
      6'd1  : phi_o = 32'h234855E5;  // theta_1 = 8.659643234e-01
      6'd2  : phi_o = 32'h1E8DAE2A;  // theta_2 = 7.498942093e-01
      6'd3  : phi_o = 32'h1A754BCE;  // theta_3 = 6.493816316e-01
      6'd4  : phi_o = 32'h16E96ECB;  // theta_4 = 5.623413252e-01
      6'd5  : phi_o = 32'h13D7416B;  // theta_5 = 4.869675252e-01
      6'd6  : phi_o = 32'h112E743F;  // theta_6 = 4.216965034e-01
      6'd7  : phi_o = 32'h0EE0E781;  // theta_7 = 3.651741273e-01
      6'd8  : phi_o = 32'h0CE26010;  // theta_8 = 3.162277660e-01
      6'd9  : phi_o = 32'h0B284679;  // theta_9 = 2.738419634e-01
      6'd10 : phi_o = 32'h09A96EB8;  // theta_10 = 2.371373706e-01
      6'd11 : phi_o = 32'h085DE780;  // theta_11 = 2.053525026e-01
      6'd12 : phi_o = 32'h073ED00D;  // theta_12 = 1.778279410e-01
      6'd13 : phi_o = 32'h0646339E;  // theta_13 = 1.539926526e-01
      6'd14 : phi_o = 32'h056EE9CF;  // theta_14 = 1.333521432e-01
      6'd15 : phi_o = 32'h04B47B37;  // theta_15 = 1.154781985e-01
      6'd16 : phi_o = 32'h041309B0;  // theta_16 = 1.000000000e-01
      6'd17 : phi_o = 32'h03873BCA;  // theta_17 = 8.659643234e-02
      6'd18 : phi_o = 32'h030E2B04;  // theta_18 = 7.498942093e-02
      6'd19 : phi_o = 32'h02A55461;  // theta_19 = 6.493816316e-02
      6'd20 : phi_o = 32'h024A8B14;  // theta_20 = 5.623413252e-02
      6'd21 : phi_o = 32'h01FBECF1;  // theta_21 = 4.869675252e-02
      6'd22 : phi_o = 32'h01B7D86D;  // theta_22 = 4.216965034e-02
      6'd23 : phi_o = 32'h017CE3F3;  // theta_23 = 3.651741273e-02
      6'd24 : phi_o = 32'h0149D668;  // theta_24 = 3.162277660e-02
      6'd25 : phi_o = 32'h011DA0A6;  // theta_25 = 2.738419634e-02
      6'd26 : phi_o = 32'h00F757DF;  // theta_26 = 2.371373706e-02
      6'd27 : phi_o = 32'h00D630C0;  // theta_27 = 2.053525026e-02
      6'd28 : phi_o = 32'h00B97B35;  // theta_28 = 1.778279410e-02
      6'd29 : phi_o = 32'h00A09EC3;  // theta_29 = 1.539926526e-02
      6'd30 : phi_o = 32'h008B1761;  // theta_30 = 1.333521432e-02
      6'd31 : phi_o = 32'h007872B9;  // theta_31 = 1.154781985e-02
      6'd32 : phi_o = 32'h00684DC5;  // theta_32 = 1.000000000e-02
      6'd33 : phi_o = 32'h005A52C7;  // theta_33 = 8.659643234e-03
      6'd34 : phi_o = 32'h004E3780;  // theta_34 = 7.498942093e-03
      6'd35 : phi_o = 32'h0043BBA3;  // theta_35 = 6.493816316e-03
      6'd36 : phi_o = 32'h003AA782;  // theta_36 = 5.623413252e-03
      6'd37 : phi_o = 32'h0032CAE5;  // theta_37 = 4.869675252e-03
      6'd38 : phi_o = 32'h002BFC0B;  // theta_38 = 4.216965034e-03
      6'd39 : phi_o = 32'h002616CC;  // theta_39 = 3.651741273e-03
      6'd40 : phi_o = 32'h0020FBD7;  // theta_40 = 3.162277660e-03
      6'd41 : phi_o = 32'h001C9011;  // theta_41 = 2.738419634e-03
      6'd42 : phi_o = 32'h0018BBFD;  // theta_42 = 2.371373706e-03
      6'd43 : phi_o = 32'h00156B46;  // theta_43 = 2.053525026e-03
      6'd44 : phi_o = 32'h00128C52;  // theta_44 = 1.778279410e-03
      6'd45 : phi_o = 32'h00100FE0;  // theta_45 = 1.539926526e-03
      6'd46 : phi_o = 32'h000DE8BD;  // theta_46 = 1.333521432e-03
      6'd47 : phi_o = 32'h000C0B79;  // theta_47 = 1.154781985e-03
      6'd48 : phi_o = 32'h000A6E2D;  // theta_48 = 1.000000000e-03
      6'd49 : phi_o = 32'h00090847;  // theta_49 = 8.659643234e-04
      6'd50 : phi_o = 32'h0007D25A;  // theta_50 = 7.498942093e-04
      6'd51 : phi_o = 32'h0006C5F7;  // theta_51 = 6.493816316e-04
      6'd52 : phi_o = 32'h0005DD8D;  // theta_52 = 5.623413252e-04
      6'd53 : phi_o = 32'h0005144A;  // theta_53 = 4.869675252e-04
      6'd54 : phi_o = 32'h00046601;  // theta_54 = 4.216965034e-04
      6'd55 : phi_o = 32'h0003CF14;  // theta_55 = 3.651741273e-04
      6'd56 : phi_o = 32'h00034C62;  // theta_56 = 3.162277660e-04
      6'd57 : phi_o = 32'h0002DB35;  // theta_57 = 2.738419634e-04
      6'd58 : phi_o = 32'h00027933;  // theta_58 = 2.371373706e-04
      6'd59 : phi_o = 32'h00022454;  // theta_59 = 2.053525026e-04
      6'd60 : phi_o = 32'h0001DAD5;  // theta_60 = 1.778279410e-04
      6'd61 : phi_o = 32'h00019B30;  // theta_61 = 1.539926526e-04
      6'd62 : phi_o = 32'h00016413;  // theta_62 = 1.333521432e-04
      6'd63 : phi_o = 32'h00013459;  // theta_63 = 1.154781985e-04
      default: phi_o = 32'h0;
    endcase
  end

endmodule
